[project]
name = "the-unlisted"
version = "1.0.3"
description = "《不在册者》VTM V5 现代之夜编年史与局势引擎"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[project.scripts]
the-unlisted = "the_unlisted.cli:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
